[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$xpn781yf$n2rgdaaOLPnLTUJGxvwZh1"
  ]

[http.routers.api]
  rule = "Host(`monitor.langbach.io.vn`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"